### ISSUE TITLE
A couple of corrections, cost calculation bug

### ISSUE THREAD

**Issue by a-fent** [bsielski/pretenders-dom5#1]
MA Mictlan has +2A +1N bonus bless points (not +1A +2N)
Teotl of the Sky (id: 2443) costs 220 and has base paths A1F1N1
Svartalf Mastersmith (id: 2802) costs 200 and has bath paths E1D1
Linnormr (id: 2801) costs 210 and has base paths W1D1

There looks to be something funny going on with the path cost calculation when the desired value is less than the base path of a pretender - the path is set to 0 in the right hand table, but additional cost is added as if this were an 'extra' path.

**Comment by bsielski** [comment]
Thanks. I fixed MA Mictlan bless points and added many missing paths for pretenders.

But I think the point costs for Pretenders you have mentioned are correct in `getPretenders.js`. Same with path cost calculation, I was aware to do this in a way that if you want less magic or Dominion strength than the base value of a chassis then you don't pay any additional costs. It maybe looks funny, but it works correctly IMO.
