### ISSUE TITLE
Blood magic>4 blanks pretender choices

### ISSUE THREAD

**Issue by svalbardcaretaker** [bsielski/pretenders-dom5#21]
Greetings, 

Just noticed that if I pick any nation and put blood>4 in, the pretender column will blank and not show a single pretender. A very recent bug, last week everything still worked fine. 

BTW thanks for maintaining, pretender calc is super valuable to me and I use it all the time!

**Comment by svalbardcaretaker** [comment]
Its not just blood. Nature and Earth alone at any number are fine, together though will blank if E>4 AND N>4. Astral blanks > 6.

**Comment by bsielski** [comment]
Thank you. I have very little time for this project now and I didn't notice that the payment  time for the server was 2 days ago. I will work on that in a few days.

**Comment by bsielski** [comment]
I can't reproduce this bug. Can you give me a screenshot?

**Comment by svalbardcaretaker** [comment]
![image](https://user-images.githubusercontent.com/11654193/117814721-f4e42c00-b264-11eb-8303-f8417f2fd9de.png)
 
With blood <4. 

![image](https://user-images.githubusercontent.com/11654193/117815366-af742e80-b265-11eb-9efd-d796d07a848e.png)


Blood => 4. 

Never mind. In the process of screenshotting I found out just now that its an issue with zoom! High zoom will make the table go to the bottom of the screen instead of the right, which I didn't notice.  Zooming out will have the table at its proper location. (900x1440 pixel screen)
