### ISSUE TITLE
Possible interface enhancements

### ISSUE THREAD

**Issue by a-fent** [bsielski/pretenders-dom5#4]
I realise the interface closely follows that of the dominions screen. That's a good thing for familiarity, but that screen is not that well designed (which is why I like using the online app). Some suggestions for enhancements:

- a "reset" button(s) for paths and scales
- somehow click on a pretender chassis or a bless to initialise path values to the minimum necessary / base (e.g. "I must have Awe" or "I must have a Solar Eagle")
- Organise the screen so the "input" areas (nation, imprisonment, paths, scales) are together and above the output areas (possible pretenders, available blesses).

**Comment by bsielski** [comment]
> a "reset" button(s) for paths and scales

done

> Organise the screen so the "input" areas (nation, imprisonment, paths, scales) are together and above the output areas (possible pretenders, available blesses).

done

> somehow click on a pretender chassis or a bless to initialise path values to the minimum necessary / base (e.g. "I must have Awe" or "I must have a Solar Eagle")

I like the idea with adding bless but it needs some clever UI design and I don't have idea how to design UI for this.

> "I must have a Solar Eagle"

I don't know how it can be helpful. Can you describe this with more detail?

**Comment by a-fent** [comment]
Thanks, the improvements are great.

With the "select a specific pretender" or "select a specific bless effect", I was thinking maybe a check-box next to the effect/pretender to lock it. But I don't know how useful this is for a pretender chassis. I know that sometimes I'm looking for a specific *type* of pretender (often, an awake monster) and want to know what's available and cheap for that nation and what might give me some useful paths. But maybe this is just easier to see in the game itself with the four tiers.
